// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://bkkbn.go.id",
        "contact": {
            "name": "Direktorat Teknologi Informasi dan Data",
            "url": "https://bkkbn.go.id",
            "email": "dittifdok@bkkbn.go.id"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cekbaduta/{nik}": {
            "get": {
                "description": "Get List Detil Keluarga yang memiliki Baduta (Bayi Usia 2 Tahun)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get List Detil Keluarga yang memiliki Baduta (Bayi Usia 2 Tahun)"
                ],
                "summary": "Get List Detil Keluarga yang memiliki Baduta (Bayi Usia 2 Tahun)",
                "operationId": "get-keluarga-baduta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nik",
                        "name": "nik",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stunting.Stunting"
                        }
                    }
                }
            }
        },
        "/cekkeluargadetail/{nik}": {
            "get": {
                "description": "Get List Detil Keluarga",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get List Detil Keluarga"
                ],
                "summary": "Get List Detil Keluarga",
                "operationId": "get-stunting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nik",
                        "name": "nik",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stunting.Stunting"
                        }
                    }
                }
            }
        },
        "/cekpushamil/{nik}": {
            "get": {
                "description": "Get List Detil Keluarga (PUS) yang sedang dalam kondisi Hamil",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get List Detil Keluarga (PUS) yang sedang dalam kondisi Hamil"
                ],
                "summary": "Get List Detil Keluarga (PUS) yang sedang dalam kondisi Hamil",
                "operationId": "get-keluarga-pus-hamil",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nik",
                        "name": "nik",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stunting.Stunting"
                        }
                    }
                }
            }
        },
        "/cekresikostunting/{nik}": {
            "get": {
                "description": "Get List Detil Keluarga yang beresiko Stunting",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get List Detil Keluarga yang beresiko Stunting"
                ],
                "summary": "Get List Detil Keluarga yang beresiko Stunting",
                "operationId": "get-keluarga-resiko-stunting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nik",
                        "name": "nik",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stunting.Stunting"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "stunting.Stunting": {
            "type": "object",
            "properties": {
                "baduta": {
                    "type": "string"
                },
                "balita": {
                    "type": "string"
                },
                "jambanLayakTidak": {
                    "type": "string"
                },
                "kodeKabupaten": {
                    "type": "integer"
                },
                "kodeKecamatan": {
                    "type": "integer"
                },
                "kodeKelurahan": {
                    "type": "integer"
                },
                "kodeProvinsi": {
                    "type": "integer"
                },
                "kodeRt": {
                    "type": "string"
                },
                "kodeRw": {
                    "type": "string"
                },
                "namaKabupaten": {
                    "type": "string"
                },
                "namaKecamatan": {
                    "type": "string"
                },
                "namaKelurahan": {
                    "type": "string"
                },
                "namaKepalaKeluarga": {
                    "type": "string"
                },
                "namaProvinsi": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "periode": {
                    "type": "integer"
                },
                "pus": {
                    "type": "string"
                },
                "pusHamil": {
                    "type": "string"
                },
                "risikoStunting": {
                    "type": "string"
                },
                "sumberAirLayakTidak": {
                    "type": "string"
                },
                "terlaluBanyak": {
                    "type": "string"
                },
                "terlaluDekat": {
                    "type": "string"
                },
                "terlaluMuda": {
                    "type": "string"
                },
                "terlaluTua": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "ds-bkkbn-p-app-ds-bkkbn-pk.apps.ocp-dev.bkkbn.go.id",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "BKKBN Digital Service Documentation",
	Description:      "Digital Service BKKBN for Integration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
