basePath: /v1/api
definitions:
  krk_kab.Krk:
    properties:
      idKabupaten:
        type: integer
      idKecamatan:
        type: integer
      idProvinsi:
        type: integer
      jumlahAirTidakLayak:
        type: integer
      jumlahBaduta:
        type: integer
      jumlahBalita:
        type: integer
      jumlahBukanPesertaKbModern:
        type: integer
      jumlahJambanTidakLayak:
        type: integer
      jumlahKeluarga:
        type: integer
      jumlahKeluargaBeresikoStunting:
        type: integer
      jumlahKeluargaSasaran:
        type: integer
      jumlahKeluargaTidakBeresikoStunting:
        type: integer
      jumlahPus:
        type: integer
      jumlahPusHamil:
        type: integer
      kodeKabupaten:
        type: string
      kodeKecamatan:
        type: string
      kodeProvinsi:
        type: string
      namaKabupaten:
        type: string
      namaKecamatan:
        type: string
      namaProvinsi:
        type: string
      peringkatKesejahteraanDiatas4:
        type: integer
      prioritas1:
        type: integer
      prioritas2:
        type: integer
      prioritas3:
        type: integer
      prioritas4:
        type: integer
    type: object
  krs_kec.Krs:
    properties:
      idKabupaten:
        type: integer
      idKecamatan:
        type: integer
      idKelurahan:
        type: integer
      idProvinsi:
        type: integer
      jumlahAirTidakLayak:
        type: integer
      jumlahBaduta:
        type: integer
      jumlahBalita:
        type: integer
      jumlahBukanPesertaKbModern:
        type: integer
      jumlahJambanTidakLayak:
        type: integer
      jumlahKeluarga:
        type: integer
      jumlahKeluargaBeresikoStunting:
        type: integer
      jumlahKeluargaSasaran:
        type: integer
      jumlahKeluargaTidakBeresikoStunting:
        type: integer
      jumlahPus:
        type: integer
      jumlahPusHamil:
        type: integer
      kodeKabupaten:
        type: string
      kodeKecamatan:
        type: string
      kodeKelurahan:
        type: string
      kodeProvinsi:
        type: string
      namaKabupaten:
        type: string
      namaKecamatan:
        type: string
      namaKelurahan:
        type: string
      namaProvinsi:
        type: string
      peringkatKesejahteraanDiatas4:
        type: integer
      prioritas1:
        type: integer
      prioritas2:
        type: integer
      prioritas3:
        type: integer
      prioritas4:
        type: integer
    type: object
  krs_nas.KrsNas:
    properties:
      idProvinsi:
        type: integer
      jumlahAirTidakLayak:
        type: integer
      jumlahBaduta:
        type: integer
      jumlahBalita:
        type: integer
      jumlahBukanPesertaKbModern:
        type: integer
      jumlahJambanTidakLayak:
        type: integer
      jumlahKeluarga:
        type: integer
      jumlahKeluargaBeresikoStunting:
        type: integer
      jumlahKeluargaSasaran:
        type: integer
      jumlahKeluargaTidakBeresikoStunting:
        type: integer
      jumlahPus:
        type: integer
      jumlahPusHamil:
        type: integer
      kodeProvinsi:
        type: string
      namaProvinsi:
        type: string
      peringkatKesejahteraanDiatas4:
        type: integer
      prioritas1:
        type: integer
      prioritas2:
        type: integer
      prioritas3:
        type: integer
      prioritas4:
        type: integer
    type: object
  krs_prov.KrsProv:
    properties:
      idKabupaten:
        type: integer
      idProvinsi:
        type: integer
      jumlahAirTidakLayak:
        type: integer
      jumlahBaduta:
        type: integer
      jumlahBalita:
        type: integer
      jumlahBukanPesertaKbModern:
        type: integer
      jumlahJambanTidakLayak:
        type: integer
      jumlahKeluarga:
        type: integer
      jumlahKeluargaBeresikoStunting:
        type: integer
      jumlahKeluargaSasaran:
        type: integer
      jumlahKeluargaTidakBeresikoStunting:
        type: integer
      jumlahPus:
        type: integer
      jumlahPusHamil:
        type: integer
      kodeKabupaten:
        type: string
      kodeProvinsi:
        type: string
      namaKabupaten:
        type: string
      namaProvinsi:
        type: string
      peringkatKesejahteraanDiatas4:
        type: integer
      prioritas1:
        type: integer
      prioritas2:
        type: integer
      prioritas3:
        type: integer
      prioritas4:
        type: integer
    type: object
host: gorest-2022-krs-ds-bkkbn-2022-gorest-krs.apps.ocp-dev.bkkbn.go.id
info:
  contact:
    email: dittifdok@bkkbn.go.id
    name: Direktorat Teknologi Informasi dan Data
    url: https://bkkbn.go.id
  description: Digital Service BKKBN for Integration
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://bkkbn.go.id
  title: BKKBN Digital Service - Rekapitulasi Keluarga Beresiko Stunting
  version: "2.1"
paths:
  /krsbykab:
    get:
      consumes:
      - '*/*'
      description: Get Aggregate Keluarga Beresiko Stunting By Kecamatan
      operationId: get-krs-by-kec
      parameters:
      - description: Province Code
        in: query
        name: kdprov
        required: true
        type: string
      - description: Kabupaten Code
        in: query
        name: kdkab
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/krk_kab.Krk'
      summary: Get Aggregate Keluarga Beresiko Stunting By Kecamatan
      tags:
      - Get Aggregate Keluarga Beresiko Stunting By Kecamatan
  /krsbykec:
    get:
      consumes:
      - '*/*'
      description: Get Aggregate Keluarga Beresiko Stunting By Kelurahan
      operationId: get-krs-by-kelurahan
      parameters:
      - description: Province Code
        in: query
        name: kdprov
        required: true
        type: string
      - description: Kabupaten Code
        in: query
        name: kdkab
        required: true
        type: string
      - description: Kecamatan Code
        in: query
        name: kdkec
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/krs_kec.Krs'
      summary: Get Aggregate Keluarga Beresiko Stunting By Kelurahan
      tags:
      - Get Aggregate Keluarga Beresiko Stunting By Kelurahan
  /krsbynas:
    get:
      consumes:
      - '*/*'
      description: Get Aggregate Keluarga Beresiko Stunting By Province
      operationId: get-krs-by-prov
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/krs_nas.KrsNas'
      summary: Get Aggregate Keluarga Beresiko Stunting By Province
      tags:
      - Get Aggregate Keluarga Beresiko Stunting By Province
  /krsbyprov:
    get:
      consumes:
      - '*/*'
      description: Get Aggregate Keluarga Beresiko Stunting By Kabupaten
      operationId: get-krs-by-kab
      parameters:
      - description: Province Code
        in: query
        name: kdprov
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/krs_prov.KrsProv'
      summary: Get Aggregate Keluarga Beresiko Stunting By Kabupaten
      tags:
      - Get Aggregate Keluarga Beresiko Stunting By Kabupaten
swagger: "2.0"
